import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'crm',
        path: '',
        title: 'Crm',
        translateKey: 'nav.crm',
        icon: 'monitor',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'crm.dashboard',
                path: '/crm/dashboard',
                title: 'Dashboard',
                translateKey: 'nav.crm.dashboard',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['asdasd'],
                subMenu: [],
            },            
            {
                key: 'crm.clienti',
                path: '/crm/clienti',
                title: 'Clienti',
                translateKey: 'nav.crm.clienti',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },            
            {
                key: 'crm.comunicazioni',
                path: '/crm/comunicazioni',
                title: 'Comunicazioni',
                translateKey: 'nav.crm.comunicazioni',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },                        
            {
                key: 'crm.calendario',
                path: '/crm/calendario',
                title: 'Calendario',
                translateKey: 'nav.crm.calendario',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'report',
                path: '/crm/report',
                title: 'Report e Statistiche',
                translateKey: 'nav.crm.report',
                icon: 'stat',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },              
        ],
    },                
    {
        key: 'vendite',
        path: '',
        title: 'Vendite',
        translateKey: 'nav.vendite',
        icon: 'cart',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'vendite.dashboard',
                path: '/vendite/dashboard',
                title: 'Dashboard',
                translateKey: 'nav.vendite.dashboard',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },            
            {
                key: 'vendite.ordini',
                path: '/vendite/ordini',
                title: 'Ordini di vendita',
                translateKey: 'nav.vendite.ordini',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },            
            {
                key: 'vendite.listini',
                path: '/vendite/listini',
                title: 'Listini',
                translateKey: 'nav.vendite.listini',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },                        
            {
                key: 'vendite.prodotti',
                path: '/vendite/prodotti',
                title: 'Prodotti',
                translateKey: 'nav.vendite.prodotti',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'vendite.tabelle',
                path: '/vendite/tabelle',
                title: 'Categorie e varianti',
                translateKey: 'nav.vendite.tabelle',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },            
        ],
    },
    {
        key: 'acquisti',
        path: '',
        title: 'Acquisti',
        translateKey: 'nav.acquisti',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'acquisti.dashboard',
                path: '/acquisti/dashboard',
                title: 'Dashboard',
                translateKey: 'nav.acquisti.dashboard',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },            
            {
                key: 'acquisti.ordini',
                path: '/acquisti/ordini',
                title: 'Ordini di acquisto',
                translateKey: 'nav.acquisti.ordini',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            }, 
            {
                key: 'acquisti.fornitori',
                path: '/acquisti/fornitori',
                title: 'Fornitori',
                translateKey: 'nav.acquisti.fornitori',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'acquisti.magazzino',
                path: '/acquisti/magazzino',
                title: 'Magazzino',
                translateKey: 'nav.acquisti.magazzino',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },                                    
        ],
    }, 
    {
        key: 'amministrazione',
        path: '',
        title: 'Amministrazione',
        translateKey: 'nav.amministrazione',
        icon: 'admin',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'amministrazione.dashboard',
                path: '/amministrazione/dashboard',
                title: 'Dashboard',
                translateKey: 'nav.amministrazione.dashboard',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },             
            {
                key: 'amministrazione.documenti',
                path: '/amministrazione/documenti',
                title: 'Fatture e Documenti',
                translateKey: 'nav.amministrazione.documenti',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'amministrazione.pagamenti',
                path: '/amministrazione/pagamenti',
                title: 'Pagamenti',
                translateKey: 'nav.amministrazione.pagamenti',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },            
        ],
    },      
    {
        key: 'sistema',
        path: '',
        title: 'Sistema',
        translateKey: 'nav.sistema',
        icon: 'setup',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'configurazione',
                path: '/sistema/configurazione',
                title: 'Configurazione',
                translateKey: 'nav.sistema.configurazione',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'account',
                path: '/sistema/account',
                title: 'Account',
                translateKey: 'nav.sistema.account',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'operatori',
                path: '/sistema/operatori',
                title: 'Operatori',
                translateKey: 'nav.sistema.operatori',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },                                  
            {
                key: 'tabelle',
                path: '/sistema/tabelle',
                title: 'Tabelle di base',
                translateKey: 'nav.tabelle',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },  
        ],
    },
]

export default navigationConfig
